import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";

// components
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "School App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={GeistSans.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
